version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
  gunicorn:
    build:
      context: .
      dockerfile: gunicorn/Dockerfile
    command: gunicorn test_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/static
    expose:
      - 8000
  web:
    build:
      context: .
      dockerfile: django/Dockerfile
    volumes:
      - static_volume:/static